# Generated by Django 3.1.7 on 2021-12-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211225_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SC_FI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_fi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='genres',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='fiction',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='sc_fi',
        ),
        migrations.AddField(
            model_name='genres',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.adventure'),
        ),
        migrations.AddField(
            model_name='genres',
            name='cr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.crime'),
        ),
        migrations.AddField(
            model_name='genres',
            name='sf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.sc_fi'),
        ),
    ]
