# Generated by Django 3.1.7 on 2021-12-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20211225_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.genres'),
        ),
    ]
