# Generated by Django 3.1.7 on 2021-12-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='sf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Adventure',
        ),
        migrations.DeleteModel(
            name='Crime',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='SC_FI',
        ),
    ]
