# Generated by Django 3.1.7 on 2022-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'star_1'), (2, 'star_2'), (3, 'star_3'), (4, 'star_4'), (5, 'star_5')], default=4),
        ),
    ]
