# Generated by Django 3.1.7 on 2022-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20220110_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_star_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=None, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='stars',
        ),
    ]
