# Generated by Django 3.1.7 on 2022-01-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20220110_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_star_system',
            name='stars',
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='star',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
