# Generated by Django 3.1.7 on 2022-01-10 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0022_auto_20220110_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_star_system',
            name='star_1',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
