# Generated by Django 3.1.7 on 2022-01-10 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0024_auto_20220110_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_star_system',
            name='star_2',
            field=models.ManyToManyField(blank=True, related_name='star_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='star_3',
            field=models.ManyToManyField(blank=True, related_name='star_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='star_4',
            field=models.ManyToManyField(blank=True, related_name='star_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='star_5',
            field=models.ManyToManyField(blank=True, related_name='star_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating_star_system',
            name='star_1',
            field=models.ManyToManyField(blank=True, related_name='star_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
