# Generated by Django 3.1.7 on 2022-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20220126_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_star_system',
            name='num_1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_5',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
