# Generated by Django 3.1.7 on 2022-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20220126_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_star_system',
            name='num_1',
            field=models.SmallIntegerField(default=1),
        ),
    ]
