# Generated by Django 3.1.7 on 2022-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20220126_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_star_system',
            name='num_2',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='rating_star_system',
            name='num_3',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='rating_star_system',
            name='num_4',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='rating_star_system',
            name='num_5',
            field=models.SmallIntegerField(default=5),
        ),
    ]
