# Generated by Django 3.1.7 on 2022-01-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20220126_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_star_system',
            name='num_1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_3',
            field=models.SmallIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_4',
            field=models.SmallIntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='rating_star_system',
            name='num_5',
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
    ]
