# Generated by Django 3.1.7 on 2022-01-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20220126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_stars',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
