# Generated by Django 3.1.7 on 2022-01-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_auto_20220126_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_stars',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='stars_of_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.users_stars'),
        ),
    ]
