# Generated by Django 3.1.7 on 2022-01-26 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_auto_20220126_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars_of_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.users_stars'),
        ),
    ]
