# Generated by Django 3.1.7 on 2022-01-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20220126_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stars_of_user',
        ),
        migrations.AddField(
            model_name='users_stars',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
