# Generated by Django 3.1.7 on 2022-04-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_auto_20220318_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_book_star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.users_stars'),
        ),
    ]
