# Generated by Django 3.1.7 on 2022-04-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_comments_user_book_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_book_star',
        ),
    ]
