# Generated by Django 3.1.7 on 2022-04-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_remove_comments_user_book_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_book_star',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.users_stars'),
        ),
    ]
